apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: PostGIS-dst
    type: postgres
    access: proxy
    url: postgis-dst:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: geodb_dst
      sslmode: disable
      postgresVersion: 1600
    editable: false
